name: Publish Docker Image
on:
  push:
    branches:
      - master
jobs:
  clang-format:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: clang-format
      run: |
        docker run --rm -v ${PWD}:/src  ghcr.io/wiiu-env/clang-format:13.0.0-2 -r ./source ./include
  build:
    runs-on: ubuntu-latest
    needs: clang-format
    steps:
    - uses: actions/checkout@master
    - name: Get release version
      id: get_release_tag
      run: |
        echo RELEASE_VERSION=$(echo $(date '+%Y%m%d')) >> $GITHUB_ENV
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ${{ GITHUB_REPOSITORY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        snapshot: true
        cache: true
        tags: "latest, ${{ env.RELEASE_VERSION }}"